version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalog_network

  catalog_service:
    build:
      context: .
      dockerfile: catalog_service/Dockerfile
    volumes:
      - ./catalog_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: catalog_db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - catalog_network

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    volumes:
      - ./user_service:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DB_NAME: user_db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - catalog_network

  notification_service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    volumes:
      - ./notification_service:/app
    ports:
      - "8005:8000"
    depends_on:
      - db
    environment:
      DB_NAME: notifications_db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - catalog_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - user_service
    networks:
      - catalog_network

volumes:
  postgres_data:

networks:
  catalog_network:
