name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  catalog_service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./catalog_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests for Catalog Service
      working-directory: ./catalog_service
      run: |
        python manage.py test

  notification_service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./notification_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests for Notification Service
      working-directory: ./notification_service
      run: |
        python manage.py test

  user_service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./user_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests for User Service
      working-directory: ./user_service
      run: |
        python manage.py test
